In [19]:
#experiment 1

In [1]:
import numpy as np
a=np.array([[2,4,6,8],[1,3,5,7]])
print(a)

[[2 4 6 8]
 [1 3 5 7]]


In [2]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
c=np.full((3,3),8)
print(c)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [6]:
d=np.random.random((2,2))
print(d)

[[0.86639957 0.43124586]
 [0.78284755 0.76229149]]


In [8]:
a=np.arange(10,60,10)
print(a)

[10 20 30 40 50]


In [9]:
a=a.reshape(5,1)
print(a)

[[10]
 [20]
 [30]
 [40]
 [50]]


In [10]:
a=a.flatten()
print(a)

[10 20 30 40 50]


In [11]:
print(a.ndim)

1


In [12]:
print(c.ndim)

2


In [13]:
print(c.shape)

(3, 3)


In [14]:
print(c.size)

9


In [15]:
print(a.dtype)

int32


In [18]:
m=c.astype('f')
print(m)

[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [20]:
#experiment 2

In [21]:
import numpy as np
arr=np.array([[-1,2,0,4],[4,0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print("Every other rows\n",arr[0:2:3])

Every other rows
 [[-1.  2.  0.  4.]]


In [22]:
t=arr[:3,:2]
print(t)

[[-1.   2. ]
 [ 4.   0.5]
 [ 2.6  0. ]]


In [23]:
c=arr<4
t=arr[c]
print(t)

[-1.   2.   0.   0.5  0.   2.6  0.   3.  -7.   2. ]


In [24]:
arr1=np.array([7,8,3])
arr2=np.array([9,1,4])
arr=np.concatenate((arr1,arr2))
print(arr)

[7 8 3 9 1 4]


In [25]:
arr=np.hstack((arr1,arr2))
arr3=np.vstack((arr1,arr2))
print(arr)
print(arr3)

[7 8 3 9 1 4]
[[7 8 3]
 [9 1 4]]


In [27]:
arr=np.array([1,2,3,4,5,6,7])
n=np.array_split(arr,5)
print(n)

[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7])]


In [28]:
#experiment 3

In [29]:
arr=np.array([1,2,3,4,5,4,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 4]
(array([3, 5, 6], dtype=int64),)


In [30]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [31]:
x=np.searchsorted(arr,3,side='left')
print(x)

4


In [32]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [33]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
new=arr[x]
print(new)

[41 43]


In [34]:
#experiment 4

In [37]:
a=np.array([10,20,30,40,50])
b=np.array([2,4,5,8,10])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))
sclr=5
print(a*sclr)

[12 24 35 48 60]
[ 8 16 25 32 40]
[ 20  80 150 320 500]
[5. 5. 6. 5. 5.]
1070
[ 50 100 150 200 250]


In [1]:
#experiment 5

In [3]:
import pandas as pd
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [6]:
emp=pd.Series(['A','B','C','D'])
id=pd.Series([1,2,3,4])
frame={'Emp':emp,'ID':id}
result=pd.DataFrame(frame)
print(result)
print("................")
print(result['Emp'])

  Emp  ID
0   A   1
1   B   2
2   C   3
3   D   4
................
0    A
1    B
2    C
3    D
Name: Emp, dtype: object


In [9]:
result['Age']=pd.Series([35,27,45,36])
print(result)

  Emp  ID  Age
0   A   1   35
1   B   2   27
2   C   3   45
3   D   4   36


In [8]:
del result['Age']
print(result)

  Emp  ID
0   A   1
1   B   2
2   C   3
3   D   4


In [10]:
print(result)

  Emp  ID  Age
0   A   1   35
1   B   2   27
2   C   3   45
3   D   4   36


In [11]:
print(result.loc[2])

Emp     C
ID      3
Age    45
Name: 2, dtype: object


In [12]:
print("\nSlice rows: \n",result[1:3])


Slice rows: 
   Emp  ID  Age
1   B   2   27
2   C   3   45


In [13]:
d2=pd.DataFrame([['x',123],['y',143]],columns=['Emp','ID'])
print(result.append(d2))

  Emp   ID   Age
0   A    1  35.0
1   B    2  27.0
2   C    3  45.0
3   D    4  36.0
0   x  123   NaN
1   y  143   NaN


C:\Users\Tcs\AppData\Local\Temp\ipykernel_6792\327924963.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(result.append(d2))


In [14]:
print(result.drop(1))

  Emp  ID  Age
0   A   1   35
2   C   3   45
3   D   4   36


In [15]:
#experiment 6

In [16]:
import numpy as np
print("DataFrame.apply function:\n")
info=pd.DataFrame([[2,7]]*3,columns=['P','Q'])
print("\noriginal dataframe\n",info)
print("\nsquare root\n",info.apply(np.sqrt))
print("\nsum of column\n",info.apply(np.sum,axis=0))
print("\nsum of row\n",info.apply(np.sum,axis=1))

DataFrame.apply function:


original dataframe
    P  Q
0  2  7
1  2  7
2  2  7

square root
           P         Q
0  1.414214  2.645751
1  1.414214  2.645751
2  1.414214  2.645751

sum of column
 P     6
Q    21
dtype: int64

sum of row
 0    9
1    9
2    9
dtype: int64


In [17]:
info=pd.DataFrame([[1,5,7],[2,7,8],[3,6,9]],columns=['X','Y','Z'])
print("\nMinimum and Maximum of each column: \n")
print(info.agg(['min','max']))


Minimum and Maximum of each column: 

     X  Y  Z
min  1  5  7
max  3  7  9


In [18]:
print(d2)

  Emp   ID
0   x  123
1   y  143


In [19]:
d2['Age']=[35,40]
d=d2.assign(sex=['M','M'])
print(d)

  Emp   ID  Age sex
0   x  123   35   M
1   y  143   40   M


In [20]:
info=pd.DataFrame(np.random.randn(5,2),index=[3,2,0,4,1],columns=['col3','col4'])
print(info)
info2=info.sort_index()
print(info2)
info3=info.sort_values(by='col3')
print(info3)

       col3      col4
3 -1.422101 -0.743776
2  1.044227 -1.018871
0 -1.663262 -0.440955
4  1.178650 -0.373668
1 -0.510942  1.571784
       col3      col4
0 -1.663262 -0.440955
1 -0.510942  1.571784
2  1.044227 -1.018871
3 -1.422101 -0.743776
4  1.178650 -0.373668
       col3      col4
0 -1.663262 -0.440955
3 -1.422101 -0.743776
1 -0.510942  1.571784
2  1.044227 -1.018871
4  1.178650 -0.373668


In [21]:
left=pd.DataFrame({
    'id':[1,2,3,4,5],
    'Name':['A','B','C','D','E'],
    'sub':['s1','s2','s3','s4','s5']
})
right=pd.DataFrame({
    'id':[1,2,3,4,5],
    'Name':['V','W','X','Y','Z'],
    'Sub':['s2','s4','s3','s6','s5'],
})
print(left)
print(right)
print(pd.merge(left,right,on='id'))

   id Name sub
0   1    A  s1
1   2    B  s2
2   3    C  s3
3   4    D  s4
4   5    E  s5
   id Name Sub
0   1    V  s2
1   2    W  s4
2   3    X  s3
3   4    Y  s6
4   5    Z  s5
   id Name_x sub Name_y Sub
0   1      A  s1      V  s2
1   2      B  s2      W  s4
2   3      C  s3      X  s3
3   4      D  s4      Y  s6
4   5      E  s5      Z  s5


In [1]:
#experiment 7

In [22]:
arr=np.array(['a','b','c','d','e','f'])
a=pd.Series(arr)
print(a)

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object


In [23]:
arr={'x':0.,'y':1.,'z':2.}
b=pd.Series(arr)
print(b)

x    0.0
y    1.0
z    2.0
dtype: float64


In [25]:
x=pd.Series(4,index=[0,1,2,3])
print(x)

0    4
1    4
2    4
3    4
dtype: int64


In [26]:
x=pd.Series([1,2,3],index=['a','b','c'])
print(x)

a    1
b    2
c    3
dtype: int64


In [27]:
a=pd.Series(data=[1,2,3,4])
print(a)
print(a.index)
print(a.values)
print(a.shape)
print(a.ndim)
print(a.size)

0    1
1    2
2    3
3    4
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[1 2 3 4]
(4,)
1
4


In [ ]:
#experiment 8

In [13]:
import pandas as pd
d=pd.read_csv("D:\employees.csv")
print(d)

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True                   NaN  
2        

In [14]:
df=pd.DataFrame(d)
print("\ncolumn heading: ",df.columns)


column heading:  Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')


In [15]:
print("\n shape: ",df.shape)


 shape:  (1000, 8)


In [17]:
print("\nparticular column value:\n ",df['Salary'])


particular column value:
  0       97308
1       61933
2      130590
3      138705
4      101004
        ...  
995    132483
996     42392
997     96914
998     60500
999    129949
Name: Salary, Length: 1000, dtype: int64


In [18]:
print("Slice table values: \n\n",df[2:5])

Slice table values: 

   First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
2             False          Finance  
3              True          Finance  
4              True  Client Services  


In [20]:
print("Particular row values: \n",df.loc[998])

Particular row values: 
 First Name                          Larry
Gender                               Male
Start Date                      4/20/2013
Last Login Time                   4:45 PM
Salary                              60500
Bonus %                            11.985
Senior Management                   False
Team                 Business Development
Name: 998, dtype: object


In [21]:
print("Get particular row value through gender \n",d.loc[d['Gender']=='Male'])

Get particular row value through gender 
     First Name Gender Start Date Last Login Time  Salary  Bonus %  \
0      Douglas   Male   8/6/1993        12:42 PM   97308    6.945   
1       Thomas   Male  3/31/1996         6:53 AM   61933    4.170   
3        Jerry   Male   3/4/2005         1:00 PM  138705    9.340   
4        Larry   Male  1/24/1998         4:47 PM  101004    1.389   
5       Dennis   Male  4/18/1987         1:35 AM  115163   10.125   
..         ...    ...        ...             ...     ...      ...   
994     George   Male  6/21/2013         5:47 PM   98874    4.479   
996    Phillip   Male  1/31/1984         6:30 AM   42392   19.675   
997    Russell   Male  5/20/2013        12:39 PM   96914    1.421   
998      Larry   Male  4/20/2013         4:45 PM   60500   11.985   
999     Albert   Male  5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True                

In [25]:
df=d['Salary']/1000
print(df)

0       97.308
1       61.933
2      130.590
3      138.705
4      101.004
        ...   
995    132.483
996     42.392
997     96.914
998     60.500
999    129.949
Name: Salary, Length: 1000, dtype: float64


In [2]:
import pandas as pd
data=pd.read_csv('D:/employees.csv')

In [3]:
type(data)

pandas.core.frame.DataFrame

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   First Name         933 non-null    object 
 1   Gender             855 non-null    object 
 2   Start Date         1000 non-null   object 
 3   Last Login Time    1000 non-null   object 
 4   Salary             1000 non-null   int64  
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object 
 7   Team               957 non-null    object 
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB


In [5]:
data

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True                   NaN  
2               False               Finance  
3                True               Finance  
4                True       Client Services  
..                ...                   ...  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales  

[1000 rows x 8 columns]

In [6]:
len(data)

1000

In [7]:
data.head()

First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170   
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858   
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340   
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [8]:
data.head(2)

First Name Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas   Male   8/6/1993        12:42 PM   97308    6.945   
1     Thomas   Male  3/31/1996         6:53 AM   61933    4.170   

  Senior Management       Team  
0              True  Marketing  
1              True        NaN

In [9]:
data.tail()

First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655   
996    Phillip   Male   1/31/1984         6:30 AM   42392   19.675   
997    Russell   Male   5/20/2013        12:39 PM   96914    1.421   
998      Larry   Male   4/20/2013         4:45 PM   60500   11.985   
999     Albert   Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales

In [10]:
data.sample(3)

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
423    Deborah  Female  11/25/1980         4:33 AM   46953   17.436   
91       James     NaN   1/26/2005        11:00 PM  128771    8.309   
293      Jesse    Male  10/25/1999         3:35 PM  118733    9.653   

    Senior Management             Team  
423             False  Client Services  
91              False              NaN  
293             False        Marketing

In [11]:
data.sample(3,random_state=2)

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
37       Linda  Female  10/19/1981         8:49 PM   57427    9.557   
726     Daniel    Male   2/29/2016         4:04 AM   77287   13.000   
846    Stephen    Male   9/10/1990        10:42 PM  129663   15.574   

    Senior Management             Team  
37               True  Client Services  
726              True              NaN  
846             False  Human Resources

In [12]:
data.columns

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [13]:
data['First Name'].head()

0    Douglas
1     Thomas
2      Maria
3      Jerry
4      Larry
Name: First Name, dtype: object

In [14]:
type(data['First Name'].head())

pandas.core.series.Series

In [15]:
data[['First Name']].head()

First Name
0    Douglas
1     Thomas
2      Maria
3      Jerry
4      Larry

In [16]:
data[['First Name','Gender']].head()

First Name  Gender
0    Douglas    Male
1     Thomas    Male
2      Maria  Female
3      Jerry    Male
4      Larry    Male

In [17]:
data_new = data.rename(columns={"First Name":"Name","Start Date":"Joining Date"})
data_new.head()

Name  Gender Joining Date Last Login Time  Salary  Bonus %  \
0  Douglas    Male     8/6/1993        12:42 PM   97308    6.945   
1   Thomas    Male    3/31/1996         6:53 AM   61933    4.170   
2    Maria  Female    4/23/1993        11:17 AM  130590   11.858   
3    Jerry    Male     3/4/2005         1:00 PM  138705    9.340   
4    Larry    Male    1/24/1998         4:47 PM  101004    1.389   

  Senior Management             Team  
0              True        Marketing  
1              True              NaN  
2             False          Finance  
3              True          Finance  
4              True  Client Services

In [ ]:
#experiment 9

In [3]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['one','two','three'],columns=['a','b','c'])
print(df)

       a  b  c
one    1  2  3
two    4  5  6
three  7  8  9


In [11]:
df.to_csv('D:\emp.csv')

In [14]:
x=pd.read_csv('D:\employees.csv')
y=pd.read_csv('D:\emp.csv')
z=x.append(y)
z.to_csv('D:\merged.csv')

C:\Users\Tcs\AppData\Local\Temp\ipykernel_5772\4091345196.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  z=x.append(y)


In [20]:
df=z.sort_values(["Salary"])
print(df)
df.to_csv('D:\sort.csv')

    First Name  Gender Start Date Last Login Time    Salary  Bonus %  \
576    Michael    Male  7/30/1993         5:35 PM   35013.0   14.879   
238      Kevin    Male  3/25/1982         7:31 AM   35061.0    5.128   
82      Steven    Male  3/30/1980         9:20 PM   35095.0    8.379   
63     Matthew    Male   1/2/2013        10:33 PM   35203.0   18.040   
650    Cynthia  Female   7/5/1986         1:24 AM   35381.0   11.749   
..         ...     ...        ...             ...       ...      ...   
429       Rose  Female  5/28/2015         8:40 AM  149903.0    5.630   
644  Katherine  Female  8/13/1996        12:21 AM  149908.0   18.912   
0          NaN     NaN        NaN             NaN       NaN      NaN   
1          NaN     NaN        NaN             NaN       NaN      NaN   
2          NaN     NaN        NaN             NaN       NaN      NaN   

    Senior Management             Team Unnamed: 0    a    b    c  
576             False          Product        NaN  NaN  NaN  NaN  
2

In [23]:
df=pd.read_csv('D:\sort.csv')
print(df)
print(list(df))
print(format(len(df)))

      Unnamed: 0.1 First Name  Gender Start Date Last Login Time    Salary  \
0              576    Michael    Male  7/30/1993         5:35 PM   35013.0   
1              238      Kevin    Male  3/25/1982         7:31 AM   35061.0   
2               82     Steven    Male  3/30/1980         9:20 PM   35095.0   
3               63    Matthew    Male   1/2/2013        10:33 PM   35203.0   
4              650    Cynthia  Female   7/5/1986         1:24 AM   35381.0   
...            ...        ...     ...        ...             ...       ...   
998            429       Rose  Female  5/28/2015         8:40 AM  149903.0   
999            644  Katherine  Female  8/13/1996        12:21 AM  149908.0   
1000             0        NaN     NaN        NaN             NaN       NaN   
1001             1        NaN     NaN        NaN             NaN       NaN   
1002             2        NaN     NaN        NaN             NaN       NaN   

      Bonus % Senior Management             Team Unnamed: 0    