In [1]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created using passed list:\n",a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [2]:
b=np.zeros((3,4))
print("\nAn array initialized with all zeros:\n",b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
c=np.full((3,3),6)
print("\nAn array initialized with all 6s.\n",c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
d=np.random.random((2,3))
print("\nA random array:\n",d)


A random array:
 [[0.31749738 0.44694862 0.46531118]
 [0.69443504 0.46506633 0.39162341]]


In [6]:
e=np.arange(0,130,15)
print("\nA sequential array with steps of 5:\n",e)


A sequential array with steps of 5:
 [  0  15  30  45  60  75  90 105 120]


In [7]:
arr=np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [8]:
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("Flattened array:\n",flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [9]:
print("\nNo.of dimensions:",arr.ndim)


No.of dimensions: 2


In [10]:
print("\nShape of array:",arr.shape)


Shape of array: (3, 4)


In [11]:
print("\nSize of array:",arr.size)


Size of array: 12


In [12]:
print("\nArray stores elements of type:",arr.dtype)


Array stores elements of type: int32


In [14]:
newtype=arr.astype("f")
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32
