In [1]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print("Original arrays")
print(a)
print(b)

Original arrays
[10 20 30 40 50]
[ 2  4  5  8 10]


In [2]:
print("\nVector addition")
print(a+b)


Vector addition
[12 24 35 48 60]


In [3]:
print("\nVector subtraction")
print(a-b)


Vector subtraction
[ 8 16 25 32 40]


In [4]:
print("\nVector multiplication")
print(a*b)


Vector multiplication
[ 20  80 150 320 500]


In [5]:
print("\nVector division")
print(a/b)


Vector division
[5. 5. 6. 5. 5.]


In [6]:
print("\nVector Dot product")
print(a.dot(b))



Vector Dot product
1070


In [7]:
print("\nscalar multiplication")
sclr=5
print("scalar value=",sclr)
print("array=",a)
print("result=",a*sclr)


scalar multiplication
scalar value= 5
array= [10 20 30 40 50]
result= [ 50 100 150 200 250]


In [8]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
print("\n\nNumpy.Vectorize method")
print("(Return x-y if x>y,otherwise return x+y)")
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("result:",vec_func(arr1,arr2))



Numpy.Vectorize method
(Return x-y if x>y,otherwise return x+y)
array1: [10, 4, 20]
array2: [2, 3, 30]
result: [ 8  1 50]
